/**
 * Type definitions for AI Coach components
 */

/**
 * Insight types from the AI Coach
 */
export type InsightType = 'daily' | 'weekly' | 'pattern' | 'session';

/**
 * An insight generated by the AI Coach
 */
export interface CoachInsight {
  id: string;
  type: InsightType;
  title: string;
  content: string;
  highlights?: string[];
  createdAt: Date;
}

/**
 * A message in the coach chat history
 */
export interface CoachMessage {
  id: string;
  role: 'user' | 'coach';
  content: string;
  createdAt: Date;
}
